### ISSUE TITLE
Support for Android Peripherals

### ISSUE THREAD

**Issue by robreuss** [robreuss/VirtualGameController#14]
A request has been made for an implementation of the Peripheral part of the framework on Android, which would enable the creation of VGC-compatible software-based controllers.  

There are a few challenges with this, but none are insurmountable:
- Service discovery to interact with the NSNetService (Bonjour) implementation on the iOS side should be straightforward to implement using Network Service Discovery on the Android side .
- For passing data values, VGC simply opens a socket and sends structured messages (i.e. a start of message indicator, type of element identifier, and the element value itself).
- Some element values are in NSData form, so the Android side will need to be able to handle that format (which I think is just a byte array).
- The DeviceInfo object passed from the Peripheral to the Central currently uses NSKeyedArchiver in binary format (NSData).  It would be easy enough to transition to using plist, for which there are parsers on the Android side.
- Some implementation of a solution for handling incoming data from the Central, presumably using the Java equivalent of blocks (closures?) as well as property inspection for use with a polling-based approach, etc.

I do not have the Android skills to do this myself, but we're hoping a developer/s will be willing to take the task on!

**Comment by RustyMoyher** [comment]
+1 to this!

If Android devices could work as peripherals, the number of supported devices would double!

**Comment by kajensen** [comment]
Agreed, this would be awesome!

**Comment by cellininicholas** [comment]
I completely agree also, this would be quite marvellous indeed! 
Anyone know any keen Android devs?

If nobody puts their hand up, my colleague and I may give it a crack eventually. We are quite keen on Android peripheral support for our game.

**Comment by darwind** [comment]
Seeing as this is still open and from January, does this mean no work has been done on it?
I'm just following the project for now, but I was hoping to get time to implement it in my game.

I'm an Android developer by the way, so was thinking of taking this task up if noone else has started it yet. I need to get a grasp on the framework though before getting my hands dirty :-)

**Comment by robreuss** [comment]
As far as I know, nobody is working on it, so it would be awesome if you did!  I've been a bit out of the loop so there are some open issues on the project, but going to try to put some attention on it in the coming weeks.

**Comment by cellininicholas** [comment]
Here is a potentially useful webpage http://jaanus.com/implementing-bonjour-across-ios-and-android/
