### ISSUE TITLE
Bluetooth Fallback

### ISSUE THREAD

**Issue by pietrodegrazia** [robreuss/VirtualGameController#21]
We are testing the sample projects with an Apple TV and an iPhone 6. Everything works fine when both Wifi and Bluetooth are on, but once I turn off Wifi the devices no longer see each other. After reading the documentation I thought it should be possible, am I wrong? Thanks

**Comment by pietrodegrazia** [comment]
The sample project was using the wrong startAs method, I have changed it to use the right one( with peer to peer) but the problem still remains.

**Comment by robreuss** [comment]
Could you test it while running the Central on an iOS device with WiFi disabled?  This may be related to the inability to disable WiFi on the Apple TV, but not sure - haven't tried it in a while.

**Comment by robreuss** [comment]
I'll test this myself today as well.
