### ISSUE TITLE
Peripheral disconnect causes EXC_BREAKPOINT

### ISSUE THREAD

**Issue by rkreutz** [robreuss/VirtualGameController#24]
Hi Rob,

as the title suggests, I'm trying to disconnect my peripheral from the central service but once I do it Xcode throws this error inside VgcBrowser.disconnectFromCentral() at vgcLogDebug()

I'm attaching an image with the error.

Thanks
![untitled](https://cloud.githubusercontent.com/assets/8869678/14294758/f8a29ada-fb48-11e5-8852-5330da7cb84b.png)

**Comment by rkreutz** [comment]
Any ideas on what may be happening and how to fix it?

**Comment by rkreutz** [comment]
I managed to avoid this error by simply commenting that line from the library source code. Most likely its a problem when calling peripheral.controller.deviceInfo.vendorName

**Comment by robreuss** [comment]
Hi Rodrigo,

Sorry about the slow response.  I've modified the logging line to remove the peripheral.controller.deviceInfo.vendorName - I was making the assumption that disconnectFromCentral was being called from the context of a bridge being used, in which case peripheral.controller would have been set.  Thanks for calling this to my attention!

Rob
