### ISSUE TITLE
Crash with app > 2 dots (.) in appIdentifier

### ISSUE THREAD

**Issue by ghost** [robreuss/VirtualGameController#26]
To recreate (tested on Apple TV):
VgcManager.startAs(.Central, appIdentifier: "1.2.3.4", includesPeerToPeer: true)

Debug Log reports:
Setting up as a CENTRAL
IncludesPeerToPeer is set to: true
Initializing Central Publisher
Publishing NetService service to listen for Peripherals on Apple TV
Central net service did not publish, error: ["NSNetServicesErrorDomain": 10, "NSNetServicesErrorCode": -72004], registered name: nil, server name: Apple TV
Republishing net service

Results in an infinite loop, leading to an memory range crash.

**Comment by robreuss** [comment]
Interesting.  The appIdentifier is included in the Bonjour service name as the "type" parameter of the method initWithDomain, so I'm guessing this may be a NSNetService-level constraint rather than a bug in the framework.  Were you able to find out more or work-around?
