### ISSUE TITLE
MFi Controllers Not Found When VgcManager Initialised post launch

### ISSUE THREAD

**Issue by ghost** [robreuss/VirtualGameController#27]
Because the app relies up listening for the GCControllerDidConnectNotification to add GCControllers to the array of VgcControllers if it's initialised post launch the notifications are missed and the controllers aren't found until they're disconnected and reconnected.

**Comment by robreuss** [comment]
Interesting.  I guess I could scan GCController.controllers array when VGC is initialized to see if there are already controllers setup there.  Does that sound like the right fix for what you are describing?
