### ISSUE TITLE
Connection question

### ISSUE THREAD

**Issue by ghost** [robreuss/VirtualGameController#29]
I am developing an Apple TV game that uses the iPhone/iPad as a game controller. I can discover the service, connect the two devices, but the VgcGameController.controllers() call on the iPhone always returns an empty array. How do I get ahold of the controller that is connected to the Apple TV (simulator)? BTW, the controllerDidConnect(notification) notification callback never gets called on the TV simulator, but it does get called on the iPhone.

Also, the only data that I want to send from the controller to the Apple TV is a CGPoint (or, if a CGPoint is not possible, an X/Y pair of Float or Int). Any ideas on the best strategy for this?

**Comment by ghost** [comment]
Revise the question above ... the iPhone shows up in the TV's controller.didConnect notification, along with an ExtendedGamePad (is this the simulator remote?). But VgcController.controllers() is always empty on the iPhone. How do I get a handle to the iPhone controller?

**Comment by robreuss** [comment]
You should be able to get a handle when didConnect fires, contained within the notification.  Do something like this:

`guard let newController: VgcController = notification.object as? VgcController else {
            vgcLogDebug("Got nil controller in controllerDidConnect")
            return
        }
`
