### ISSUE TITLE
Rob, can you look at the PRs ?

### ISSUE THREAD

**Issue by orff** [robreuss/VirtualGameController#30]
This project is starting to look pretty stale ( and its awesome! )

**Comment by robreuss** [comment]
Hey Mike.  Sorry I haven't done any updates - been taking a break from development work.  I'll pull those.  If you're willing to help maintain that would be great!  :)

**Comment by orff** [comment]
I don't know the code as well as you do, but I would be happy to help validate some of the incoming PRs for you and add a few things.  I will ask at my company to see if anyone else wants to pitch in as well.  Reply to my email on gmail and we can take it from there ...
